apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis-chat-redis
    deployment: redis-chat
  name: redis-chat-redis-service
spec:
  ports:
  - port: 6379
    name: redis
  selector:
    app: redis-chat-redis
